BLAS/LAPACK in C and C++: test_blas.cc File Reference
test_blas.cc File Reference
#include <cassert>
#include <iostream>
#include <vector>
#include "cblas.h"
#include "my_blas_implementation.h"
Functions
void test_cblas_sscal ()
int main ()
Function Documentation
main()
int main ()
Definition at line 98 of file test_blas.cc.
            {
   test_cblas_sscal();
   return 0;
 }
References test_cblas_sscal().
test_cblas_sscal()
void test_cblas_sscal ()
Definition at line 25 of file test_blas.cc.
{
   std::cout << "==========cblas_sscal==========" << std::endl;
   std::vector<float> x = {0, 1, 2, 3};
   std::vector<float> y = x;
   float alpha = 10;
   // case 1: incx is 1
   // scale every element of x by 10
   cblas_sscal(4, alpha, x.data(), 1);
   kk::level1::sscal(4, alpha, y.data(), 1);
   assert(x == y);
   assert(x[0] == 0);   // 0 * 10
   assert(x[1] == 10);  // 1 * 10
   assert(x[2] == 20);  // 2 * 10
   assert(x[3] == 30);  // 3 * 10
   // case 2: incx is 2
   // scale every second element of x by 100
   alpha = 100;
   cblas_sscal(2, alpha, x.data(), 2);
   kk::level1::sscal(2, alpha, y.data(), 2);
   assert(x == y);
   assert(x[0] == 0);
   assert(x[1] == 10);    // not changed
   assert(x[2] == 2000);  // scaled by 100, 20*100
   assert(x[3] == 30);    // not changed
   std::cout << "==========cblas_sscal OK==========" << std::endl;
 }
References cblas_sscal(), and kk::level1::sscal().
Referenced by main().