BLAS/LAPACK in C and C++: Level 1 functions.
Level 1 functions.
Level 1 functions in BLAS.
Functions
float kk::level1::sasum (const int N, const float *X, const int incX)
Sum of the absolute values of a vector: y = sum(abs(x[:]))
void kk::level1::saxpy (const int N, const float alpha, const float *X, const int incX, float *Y, const int incY)
Y = alpha * X + Y.
void kk::level1::scopy (const int N, const float *X, const int incX, float *Y, const int incY)
copy a vector: y = x
float kk::level1::sdot (const int N, const float *X, const int incX, const float *Y, const int incY)
dot product of a vector: s = dot(x, y)
float kk::level1::snrm2 (const int N, const float *X, const int incX)
Return the 2-norm of a vector.
void kk::level1::sscal (const int N, const float alpha, float *X, const int incX)
scale x with alpha.
void kk::level1::sswap (const int N, float *X, const int incX, float *Y, const int incY)
swap two vectors
CBLAS_INDEX kk::level1::isamax (const int N, const float *X, const int incX)
Return the index i such that abs(X[i*incX]) is the maximum.
Detailed Description
Level 1 functions in BLAS.
y = sum(abs(x[:]))
y = alpha * x + y
y = x
y = alpha * y
s = dot(x, y)
Note
x and y can be the same; that is, it can be an inplace operation.
Refer to https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms#Level_1 for the classification of BLAS levels.
Function Documentation
isamax()
CBLAS_INDEX kk::level1::isamax (const int N, const float * X, const int incX)
Return the index i such that abs(X[i*incX]) is the maximum.
The naming convention of isamax
i: the return value is an integer
s: single float precision
amax: short for **a**bsolute max
Example: for an array [0, 1, 2, -3]
if N = 4, incX=1, then it returns 3 (zero based index, the largest absolute value 3 is at position 3, [0, 1, 2, -3])
if N = 2, incX=2, then it returns 1 (zero based index, the largest absolute value 2 is at position 1, with stride 2, [0, 2])
Parameters
N number of elements in X
X the vector X
incX the stride in X
Returns
the index i such that X[i*incX] is the maximum
Warning
it should be CBLAS_INDEX, which is platform dependent macro
Definition at line 87 of file my_blas_implementation.cc.
{
   CBLAS_INDEX res = 0;
   float max_val = fabsf(*X);
   for (int i = 0; i < N; ++i) {
     if (fabsf(*X) > max_val) {
       res = i;  // is is the index of the element
       max_val = fabsf(*X);
     }
     X += incX;
   }
   return res;
 }
References CBLAS_INDEX.
Referenced by test_cblas_isamax().
sasum()
float kk::level1::sasum (const int N, const float * X, const int incX)
Sum of the absolute values of a vector: y = sum(abs(x[:]))
Parameters
N number of elements in X
X the vector
incX the stride in X
Returns
the sum of absolute value of all elements in X
Warning
a in sasum means absolute
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-asum
http://www.netlib.org/blas/sasum.f
Definition at line 23 of file my_blas_implementation.cc.
{
   float s = 0;
   for (int i = 0; i < N; ++i) {
     s += fabs(*X);
     X += incX;
   }
   return s;
 }
Referenced by test_cblas_sasum().
saxpy()
void kk::level1::saxpy (const int N, const float alpha, const float * X, const int incX, float * Y, const int incY)
Y = alpha * X + Y.
axpy is short for a*x plus y
Parameters
N number of elements in X and Y
alpha the scale
X the vector X
incX the stride for X
Y the vector Y
incY the stride for Y
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-axpy
http://www.netlib.org/blas/saxpy.f
Definition at line 32 of file my_blas_implementation.cc.
{
   for (int i = 0; i < N; ++i) {
     *Y += *X * alpha;
     X += incX;
     Y += incY;
   }
 }
Referenced by test_cblas_saxpy().
scopy()
void kk::level1::scopy (const int N, const float * X, const int incX, float * Y, const int incY)
copy a vector: y = x
Parameters
N number of elements in X
X the src vector
incX the stride in X
Y the dst vector
incY the stride in Y
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-copy
http://www.netlib.org/blas/scopy.f
Definition at line 41 of file my_blas_implementation.cc.
{
   for (int i = 0; i < N; ++i) {
     *Y = *X;
     X += incX;
     Y += incY;
   }
 }
Referenced by test_cblas_scopy().
sdot()
float kk::level1::sdot (const int N, const float * X, const int incX, const float * Y, const int incY)
dot product of a vector: s = dot(x, y)
Compute the dot product of two vectors.
Parameters
N number of elements in X and Y
X the vector X
incX the stride of vector X
Y the vector Y
incY the stride of vector Y
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-dot
http://www.netlib.org/blas/sdot.f
Definition at line 50 of file my_blas_implementation.cc.
{
   float p = 0;
   for (int i = 0; i < N; ++i) {
     p += (*X) * (*Y);
     X += incX;
     Y += incY;
   }
   return p;
 }
Referenced by test_cblas_sdot().
snrm2()
float kk::level1::snrm2 (const int N, const float * X, const int incX)
Return the 2-norm of a vector.
Compute s = sqrt(dot(X, X))
Parameters
N number of elements in the vector X
X the vector
incX the stride in X
Returns
sqrt(dot(X, X))
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-nrm2
http://www.netlib.org/blas/snrm2.f
Definition at line 61 of file my_blas_implementation.cc.
{
   float s = 0;
   for (int i = 0; i < N; ++i) {
     s += (*X) * (*X);
     X += incX;
   }
   return sqrtf(s);
 }
Referenced by test_cblas_snrm2().
sscal()
void kk::level1::sscal (const int N, const float alpha, float * X, const int incX)
scale x with alpha.
for i in range(N):
  X[i * incX] *= alpha
Parameters
N number of elements in X
alpha the scale
X a vector
incX the stride between two elements in X
Warning
this is an inplace operation
Refer to
https://software.intel.com/en-us/mkl-developer-reference-c-cblas-scal
http://www.netlib.org/blas/sscal.f
Definition at line 70 of file my_blas_implementation.cc.
{
   for (int i = 0; i < N; ++i) {
     *X *= alpha;
     X += incX;
   }
 }
Referenced by test_cblas_sscal().
sswap()
void kk::level1::sswap (const int N, float * X, const int incX, float * Y, const int incY)
swap two vectors
Parameters
N number of elements in X and Y
X the vector X
incX the stride in X
Y the vector Y
incY the stride in Y
Refer to
https://software.intel.com/en-us/onemkl-developer-reference-c-cblas-swap
http://www.netlib.org/blas/sswap.f
Definition at line 77 of file my_blas_implementation.cc.
{
   for (int i = 0; i < N; ++i) {
     float tmp = *X;
     *X = *Y;
     *Y = tmp;
     X += incX;
     Y += incY;
   }
 }
Referenced by test_cblas_sswap().