OpenCNN: cnn Namespace Reference
cnn Namespace Reference
Classes
class Array
class ArrayMathTest
class ArrayTest
class ArrayWithOp
class Jet
Jet for autodiff (forward mode).
class JetTest
Typedefs
using MyTypes = ::testing::Types< float, double >
Functions
template<typename Dtype >
Dtype ax_sub_by_squared (int n, Dtype alpha, const Dtype *x, Dtype beta, const Dtype *y)
compute (alpha*x[0]-beta*y[0])**2 + (alpha*x[1]-beta*y[1])**2
template<typename Dtype >
Dtype ax_dot_by (int n, Dtype alpha, const Dtype *x, Dtype beta, const Dtype *y)
Compute the dot product between alpha*x and beta*y; alpha*x[0]*beta*y[0] + ...
template<typename Dtype >
void ax_plus_by (int n, Dtype alpha, const Dtype *x, Dtype beta, Dtype *y)
y[i] = alpha*x[i] + beta*y[i]
template<typename Dtype >
void set_to (Array< Dtype > *arr, Dtype val)
Set all elements of the array to the specified value.
template<typename Dtype >
void set_to (int n, Dtype *arr, Dtype val)
template<typename Dtype >
void scale_arr (Dtype alpha, const Array< Dtype > &src, Array< Dtype > *dst)
dst[i] = alpha * src[i]
template<typename Dtype >
void scale_arr (int n, Dtype alpha, const Dtype *src, Dtype *dst)
template<typename Dtype >
Dtype sum_arr (const Array< Dtype > &src)
res = src[0] + src[1] + src[2] + ...
template<typename Dtype >
Dtype sum_arr (int n, const Dtype *src)
template<typename Dtype >
Dtype sum_squared_arr (int n, const Dtype *src)
template<typename Dtype >
void sub_scalar (Dtype alpha, const Array< Dtype > &src, Array< Dtype > *dst)
dst[i] = src[i] - alpha
template<typename Dtype >
void sub_scalar (int n, Dtype alpha, const Dtype *src, Dtype *dst)
dst[i] = src[i] - alpha
TYPED_TEST_CASE (ArrayTest, MyTypes)
template<typename Dtype >
bool isAllZeros (const Array< Dtype > &arr)
TYPED_TEST (ArrayTest, default_constructor)
TYPED_TEST (ArrayTest, init)
TYPED_TEST (ArrayTest, at)
TYPED_TEST (ArrayTest, operator_paren)
TYPED_TEST (ArrayTest, operator_bracket)
TYPED_TEST (ArrayTest, operators)
TYPED_TEST (ArrayTest, proto)
TYPED_TEST (ArrayTest, move_constructor)
TYPED_TEST (ArrayTest, move_assignment)
TYPED_TEST_CASE (ArrayMathTest, MyTypes)
TYPED_TEST (ArrayMathTest, set_to)
TYPED_TEST (ArrayMathTest, ax_sub_by_squared)
TYPED_TEST (ArrayMathTest, ax_dot_by)
TYPED_TEST (ArrayMathTest, scale_arr)
TYPED_TEST (ArrayMathTest, sum_arr)
TYPED_TEST (ArrayMathTest, sum_arr2)
TYPED_TEST (ArrayMathTest, sum_squared_arr)
TYPED_TEST (ArrayMathTest, sub_scalar)
TYPED_TEST (ArrayMathTest, sub_scalar2)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator+ (const ArrayWithOp< Dtype, N > &a, const ArrayWithOp< Dtype, N > &b)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator- (const ArrayWithOp< Dtype, N > &a, const ArrayWithOp< Dtype, N > &b)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator- (const ArrayWithOp< Dtype, N > &a)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator* (const ArrayWithOp< Dtype, N > &a, double s)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator* (double s, const ArrayWithOp< Dtype, N > &a)
template<typename Dtype , int N>
ArrayWithOp< Dtype, N > operator/ (const ArrayWithOp< Dtype, N > &a, double s)
template<typename Dtype , int N>
std::ostream & operator<< (std::ostream &os, const Jet< Dtype, N > &f)
template<typename Dtype , int N>
Jet< Dtype, N > operator- (const Jet< Dtype, N > &f)
Negate a jet.
template<typename Dtype , int N>
Jet< Dtype, N > operator+ (const Jet< Dtype, N > &f, Dtype s)
Jet + scalar.
template<typename Dtype , int N>
Jet< Dtype, N > operator+ (Dtype s, const Jet< Dtype, N > &f)
scalar + jet
template<typename Dtype , int N>
Jet< Dtype, N > operator- (const Jet< Dtype, N > &f, Dtype s)
jet - scalar
template<typename Dtype , int N>
Jet< Dtype, N > operator- (Dtype s, const Jet< Dtype, N > &f)
scalar - jet
template<typename Dtype , int N>
Jet< Dtype, N > operator* (const Jet< Dtype, N > &f, Dtype s)
jet * scalar
template<typename Dtype , int N>
Jet< Dtype, N > operator* (Dtype s, const Jet< Dtype, N > &f)
scalar * jet
template<typename Dtype , int N>
Jet< Dtype, N > operator/ (const Jet< Dtype, N > &f, Dtype s)
jet / s
template<typename Dtype , int N>
Jet< Dtype, N > operator/ (Dtype s, const Jet< Dtype, N > &f)
\(\frac{s}{jet}\)
template<typename Dtype , int N>
Jet< Dtype, N > operator+ (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
jet + jet
template<typename Dtype , int N>
Jet< Dtype, N > operator- (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
jet - jet
template<typename Dtype , int N>
Jet< Dtype, N > operator* (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
@bref jet * jet
template<typename Dtype , int N>
Jet< Dtype, N > operator/ (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
\frac{jet}{jet}
template<typename Dtype , int N>
bool operator== (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
compare two jets: jet1 == jet2
template<typename Dtype , int N>
bool operator!= (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
Compare two jets: jet1 != jet2.
template<typename Dtype , int N>
bool operator< (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
Compare two jets: jet1 < jet2.
template<typename Dtype , int N>
bool operator<= (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
Compare two jets: jet1 <= jet2.
template<typename Dtype , int N>
bool operator> (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
Compare two jets: jet1 > jet2.
template<typename Dtype , int N>
bool operator>= (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
Compare two jets: jet1 >= jet2.
template<typename Dtype , int N>
Jet< Dtype, N > max (const Jet< Dtype, N > &f, const Jet< Dtype, N > &g)
max(jet1, jet2)
template<typename Dtype , int N>
Jet< Dtype, N > exp (const Jet< Dtype, N > &f)
exp(jet)
template<typename Dtype , int N>
Jet< Dtype, N > log (const Jet< Dtype, N > &f)
log(jet)
template<typename Dtype , int N>
Jet< Dtype, N > sqrt (const Jet< Dtype, N > &f)
sqrt(jet)
TYPED_TEST_CASE (JetTest, MyTypes)
template<typename Dtype >
Dtype add_scalar1 (const Dtype &x)
template<typename Dtype >
Dtype add_scalar2 (const Dtype &x)
template<typename Dtype >
Dtype add_scalar3 (const Dtype &x)
template<typename Dtype >
Dtype sub_scalar1 (const Dtype &x)
template<typename Dtype >
Dtype sub_scalar2 (const Dtype &x)
template<typename Dtype >
Dtype sub_scalar3 (const Dtype &x)
template<typename Dtype >
Dtype mul_scalar1 (const Dtype &x)
template<typename Dtype >
Dtype mul_scalar2 (const Dtype &x)
template<typename Dtype >
Dtype mul_scalar3 (const Dtype &x)
template<typename Dtype >
Dtype div_scalar1 (const Dtype &x)
template<typename Dtype >
Dtype div_scalar2 (const Dtype &x)
template<typename Dtype >
Dtype div_scalar3 (const Dtype &x)
template<typename Dtype >
Dtype jet_mul_div_add (const Dtype &x, const Dtype &y)
template<typename Dtype >
Dtype jet_sub_div (const Dtype &x, const Dtype &y)
TYPED_TEST (JetTest, scalar_add)
TYPED_TEST (JetTest, scalar_sub)
TYPED_TEST (JetTest, negate)
TYPED_TEST (JetTest, scalar_mul)
TYPED_TEST (JetTest, scalar_div)
TYPED_TEST (JetTest, jet_mul_div_add_test)
TYPED_TEST (JetTest, jet_sub_div)
TYPED_TEST (JetTest, jet_exp_log)
TYPED_TEST (JetTest, jet_sqrt)
Typedef Documentation
MyTypes
typedef::testing::Types< float, double > cnn::MyTypes
Definition at line 24 of file test_array.cc.
Function Documentation
add_scalar1()
template<typename Dtype > Dtype cnn::add_scalar1 (const Dtype & x)
Definition at line 18 of file test_jet.cc.
{
   Dtype y;
   y = x + Dtype(1);
   return y;
 }
Referenced by TYPED_TEST().
add_scalar2()
template<typename Dtype > Dtype cnn::add_scalar2 (const Dtype & x)
Definition at line 26 of file test_jet.cc.
{
   Dtype y;
   y = Dtype(1) + x;
   return y;
 }
Referenced by TYPED_TEST().
add_scalar3()
template<typename Dtype > Dtype cnn::add_scalar3 (const Dtype & x)
Definition at line 34 of file test_jet.cc.
{
   Dtype y(x);
   y += Dtype(1);
   return y;
 }
ax_dot_by()
template<typename Dtype > Dtype cnn::ax_dot_by (int n, Dtype alpha, const Dtype * x, Dtype beta, const Dtype * y)
Compute the dot product between alpha*x and beta*y; alpha*x[0]*beta*y[0] + ...
alpha*x[n-1]*beta*y[n-1]
Parameters
n number of elements in x and y
alpha every element in x is scaled by alpha
x an array of n elements
beta every element in y is scaled by beta
y an array of n elements
Returns
\[ sum_{i=0}^{n-1} (\alpha x[i] + \beta y[i]) \]
Definition at line 58 of file array_math.h.
{
   Dtype res = 0;
   for (int i = 0; i < n; i++) {
     res += alpha * x[i] * beta * y[i];
   }
   return res;
 }
ax_plus_by()
template<typename Dtype > void cnn::ax_plus_by (int n, Dtype alpha, const Dtype * x, Dtype beta, Dtype * y)
y[i] = alpha*x[i] + beta*y[i]
Parameters
n number of elements
alpha every element in x is scaled by alpha
x an array of n elements
beta every element in y is scaled by beta
y an array of n elements
Returns
void
Definition at line 77 of file array_math.h.
{
   for (int i = 0; i < n; i++) {
     y[i] = alpha * x[i] + beta * y[i];
   }
 }
ax_sub_by_squared()
template<typename Dtype > Dtype cnn::ax_sub_by_squared (int n, Dtype alpha, const Dtype * x, Dtype beta, const Dtype * y)
compute (alpha*x[0]-beta*y[0])**2 + (alpha*x[1]-beta*y[1])**2
... + (alpha*x[n-1]-beta*y[n-1])**2
Parameters
n number of elements in x and y
alpha every element in x is scaled by alpha
x an array of n elements
beta every element in y is scaled by beta
y an array of n elements
Returns
\[\sum_{i=0}^{n-1} (\alpha x[i] - \beta y[i])^2 \]
Definition at line 36 of file array_math.h.
{
   Dtype res = 0;
   for (int i = 0; i < n; i++) {
     Dtype diff = alpha * x[i] - beta * y[i];
     res += diff * diff;
   }
   return res;
 }
div_scalar1()
template<typename Dtype > Dtype cnn::div_scalar1 (const Dtype & x)
Definition at line 90 of file test_jet.cc.
{
   Dtype y;
   y = x / Dtype(2);
   return y;
 }
Referenced by TYPED_TEST().
div_scalar2()
template<typename Dtype > Dtype cnn::div_scalar2 (const Dtype & x)
Definition at line 98 of file test_jet.cc.
{
   Dtype y;
   y = Dtype(2) / x;
   return y;
 }
Referenced by TYPED_TEST().
div_scalar3()
template<typename Dtype > Dtype cnn::div_scalar3 (const Dtype & x)
Definition at line 106 of file test_jet.cc.
{
   Dtype y(x);
   y /= Dtype(2);
   return y;
 }
Referenced by TYPED_TEST().
exp()
template<typename Dtype , int N> Jet<Dtype, N> cnn::exp (const Jet< Dtype, N > & f)
exp(jet)
Assume \(f = x + \epsilon \cdot f_x\), then the derivative of \(\mathrm{e}^f\) with respect to x is \(\mathrm{e}^f \cdot f_x\).
Thus, we should return a jet (exp(value), exp(value)*grad)
Parameters
f the input jet
Returns
a jet with (exp(value), exp(value)*grad)
Definition at line 576 of file jet.h.
{
   Jet<Dtype, N> res;
   auto s = exp(f.val_);
   res.val_ = s;
   res.grad_ = s * f.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
Referenced by TYPED_TEST().
isAllZeros()
template<typename Dtype > bool cnn::isAllZeros (const Array< Dtype > & arr)
Definition at line 28 of file test_array.cc.
{
   for (int i = 0; i < arr.total_; i++) {
     if (arr.d_[i]) return false;
   }
   return true;
 }
References cnn::Array< Dtype >::d_, and cnn::Array< Dtype >::total_.
Referenced by TYPED_TEST().
jet_mul_div_add()
template<typename Dtype > Dtype cnn::jet_mul_div_add (const Dtype & x, const Dtype & y)
Definition at line 113 of file test_jet.cc.
{
   Dtype z;
   z = x * y / (x * x + y);
   return z;
   // from https://www.whitman.edu/mathematics/calculus_online/section14.03.html
   /*
    * dz/dx = (y*y - x*x*y)/((x*x+y)*(x*x+y))
    * dz/dy = x*x*x/((x*x+y)*(x*x+y))
    */
 }
Referenced by TYPED_TEST().
jet_sub_div()
template<typename Dtype > Dtype cnn::jet_sub_div (const Dtype & x, const Dtype & y)
Definition at line 125 of file test_jet.cc.
{
   Dtype z;
   z = (x - y) / (x + y);
   return z;
   // http://math.gmu.edu/~memelian/teaching/Fall08/partDerivExamples.pdf
   // 1 (e)
   /*
    * dz/dx = 2y/((x+y)*(x+y))
    * dz/dy = -2x/((x+y)*(x+y))
    */
 }
Referenced by TYPED_TEST().
log()
template<typename Dtype , int N> Jet<Dtype, N> cnn::log (const Jet< Dtype, N > & f)
log(jet)
Assume \(f = x + \epsilon \cdot f_x\), then the derivative of \(\mathrm{log}(f)\) with respect to x is \(\frac{1}{f} \cdot f_x\).
Thus, we should return a jet (log(value), \(\frac{1}{\mathrm{value}}\)*grad)
Returns
a jet (log(value), \(\frac{1}{\mathrm{value}}\)*grad)
Definition at line 600 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = log(f.val_);
   res.grad_ = f.grad_ / f.val_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
Referenced by TYPED_TEST().
max()
template<typename Dtype , int N> Jet<Dtype, N> cnn::max (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
max(jet1, jet2)
Parameters
f the first jet
g the second jet
Warning
It returns by value!
Returns
g if f.val < g.val; f otherwise
Definition at line 558 of file jet.h.
{
   return (f < g) ? g : f;
 }
mul_scalar1()
template<typename Dtype > Dtype cnn::mul_scalar1 (const Dtype & x)
Definition at line 66 of file test_jet.cc.
{
   Dtype y;
   y = x * Dtype(2);
   return y;
 }
Referenced by TYPED_TEST().
mul_scalar2()
template<typename Dtype > Dtype cnn::mul_scalar2 (const Dtype & x)
Definition at line 74 of file test_jet.cc.
{
   Dtype y;
   y = Dtype(2) * x;
   return y;
 }
Referenced by TYPED_TEST().
mul_scalar3()
template<typename Dtype > Dtype cnn::mul_scalar3 (const Dtype & x)
Definition at line 82 of file test_jet.cc.
{
   Dtype y(x);
   y *= Dtype(2);
   return y;
 }
Referenced by TYPED_TEST().
operator!=()
template<typename Dtype , int N> bool cnn::operator!= (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
Compare two jets: jet1 != jet2.
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if the values of the two jet are NOT equal; false otherwise
Definition at line 475 of file jet.h.
{
   return f.val_ != g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
operator*() [1/5]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator* (const ArrayWithOp< Dtype, N > & a, double s)
Definition at line 68 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = a[i] * s;
   }
   return c;
 }
operator*() [2/5]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator* (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
@bref jet * jet
Parameters
f the first jet
g the second jet
\[ (x + \epsilon f_x)\cdot(y + \epsilon f_y) = xy + \epsilon (x\cdot f_y + y\cdot f_x) + \epsilon^2 (f_x \cdot f_y) \]
Since \(\epsilon^2 == 0\), we have
\[ (x + \epsilon f_x)\cdot(y + \epsilon f_y) = xy + \epsilon (x\cdot f_y + y\cdot f_x) \]
So we should return a jet \((\mathrm{f.val} \times \mathrm{g.val}, x\times\mathrm{g.grad} + y\times\mathrm{f.grad})\)
Returns
a jet \((\mathrm{f.val} \times\mathrm{g.val}, \mathrm{f.val}\times\mathrm{g.grad} + \mathrm{g.val}\times\mathrm{f.grad})\)
Definition at line 410 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ * g.val_;
   res.grad_ = f.val_ * g.grad_ + g.val_ * f.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator*() [3/5]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator* (const Jet< Dtype, N > & f, Dtype s)
jet * scalar
Parameters
f the input jet
s the scalar
Note
the gradient is scaled by s
Returns
a jet with (s * value, s * gradient)
Definition at line 287 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ * s;
   res.grad_ = f.grad_ * s;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator*() [4/5]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator* (double s, const ArrayWithOp< Dtype, N > & a)
Definition at line 77 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = a[i] * s;
   }
   return c;
 }
operator*() [5/5]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator* (Dtype s, const Jet< Dtype, N > & f)
scalar * jet
Parameters
s the scalar
f the input jet
Note
the gradient is scaled by s
Returns
a jet with (s * value, s * gradient)
Definition at line 305 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ * s;
   res.grad_ = f.grad_ * s;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator+() [1/4]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator+ (const ArrayWithOp< Dtype, N > & a, const ArrayWithOp< Dtype, N > & b)
Definition at line 39 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = a[i] + b[i];
   }
   return c;
 }
operator+() [2/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator+ (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
jet + jet
Parameters
f the first jet
g the second jet
Returns
(f.val + g.val, f.grad + g.grad)
Definition at line 365 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ + g.val_;
   res.grad_ = f.grad_ + g.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator+() [3/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator+ (const Jet< Dtype, N > & f, Dtype s)
Jet + scalar.
Parameters
f the input jet
s the scalar
Note
the gradient is not changed and only the value is increased by s.
Returns
a jet with (s + value, gradient)
Definition at line 220 of file jet.h.
{
   Jet<Dtype, N> res(f);
   res.val_ += s;
   return res;
 }
References cnn::Jet< Dtype, N >::val_.
operator+() [4/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator+ (Dtype s, const Jet< Dtype, N > & f)
scalar + jet
Parameters
s the scalar
f the in jet
Note
the gradient is not changed and only the value is increased by s.
Returns
a jet with (s + value, gradient)
Definition at line 237 of file jet.h.
{
   Jet<Dtype, N> res(f);
   res.val_ += s;
   return res;
 }
References cnn::Jet< Dtype, N >::val_.
operator-() [1/6]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator- (const ArrayWithOp< Dtype, N > & a)
Definition at line 59 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = -a[i];
   }
   return c;
 }
operator-() [2/6]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator- (const ArrayWithOp< Dtype, N > & a, const ArrayWithOp< Dtype, N > & b)
Definition at line 49 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = a[i] - b[i];
   }
   return c;
 }
operator-() [3/6]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator- (const Jet< Dtype, N > & f)
Negate a jet.
Parameters
f the input jet
Returns
a jet with (-value, -gradient) of the input jet
Definition at line 197 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = -f.val_;
   res.grad_ = -f.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator-() [4/6]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator- (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
jet - jet
Parameters
f the first jet
g the second jet
Returns
(f.val - g.val, f.grad - g.grad)
Definition at line 380 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ - g.val_;
   res.grad_ = f.grad_ - g.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator-() [5/6]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator- (const Jet< Dtype, N > & f, Dtype s)
jet - scalar
Parameters
f the input jet
s the scalar
Note
the gradient is not changed
Returns
a jet with (val - s, gradient)
Definition at line 254 of file jet.h.
{
   Jet<Dtype, N> res(f);
   res.val_ -= s;
   return res;
 }
References cnn::Jet< Dtype, N >::val_.
operator-() [6/6]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator- (Dtype s, const Jet< Dtype, N > & f)
scalar - jet
Parameters
s the scalar
f the input jet
Note
the gradient is negated
Returns
a jet with (s - value, -gradient)
Definition at line 270 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = s - f.val_;
   res.grad_ = -f.grad_;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator/() [1/4]
template<typename Dtype , int N> ArrayWithOp<Dtype, N> cnn::operator/ (const ArrayWithOp< Dtype, N > & a, double s)
Definition at line 86 of file jet.h.
{
   ArrayWithOp<Dtype, N> c;
   for (int i = 0; i < N; ++i) {
     c[i] = a[i] / s;
   }
   return c;
 }
operator/() [2/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator/ (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
\frac{jet}{jet}
Parameters
f the first jet (numerator)
g the second jet (denominator)
\[ \frac{x + \epsilon \cdot f_x}{y + \epsilon \cdot f_y} =\frac{(x+\epsilon \cdot f_x)(y - \epsilon \cdot f_y)}{(y+\epsilon\cdot f_y)(y-\epsilon\cdot f_y)} = \frac{x\cdot y + \epsilon(y\cdot f_x - x\cdot f_y) - \epsilon^2 f_x f_y}{y^2 - \epsilon^2 f_y^2} \]
Since \(\epsilon^2 == 0\), we have
\[ \frac{x + \epsilon \cdot f_x}{y + \epsilon \cdot f_y} = \frac{x\cdot y + \epsilon(y\cdot f_x - x\cdot f_y)}{y^2} = \frac{x}{y} + \epsilon (\frac{f_x}{y} - \frac{x \cdot f_y}{y^2}) \]
Returns
a jet \((\frac{\mathrm{f.val}}{\mathrm{g.val}}, \frac{\mathrm{f.grad}}{\mathrm{g.val}} - \frac{\mathrm{f.val}\times\mathrm{g.grad}}{\mathrm{g.val}^2})\)
Definition at line 442 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ / g.val_;
   res.grad_ = f.grad_ / g.val_ - (f.val_ * g.grad_) / (g.val_ * g.val_);
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator/() [3/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator/ (const Jet< Dtype, N > & f, Dtype s)
jet / s
Parameters
f the input jet
s the scalar
Note
the gradient is scaled by (1/s)
Returns
a jet with (value/s, gradient/s)
Definition at line 322 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = f.val_ / s;
   res.grad_ = f.grad_ / s;
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator/() [4/4]
template<typename Dtype , int N> Jet<Dtype, N> cnn::operator/ (Dtype s, const Jet< Dtype, N > & f)
\(\frac{s}{jet}\)
\[ \frac{s}{x + \epsilon\cdot g} = \frac{s(x - \epsilon\cdot g)}{(x + \epsilon\cdot g)(x - \epsilon\cdot g)} = \frac{s \cdot x - \epsilon\cdot s g}{x^2 - \epsilon^2\cdot g^2} \]
Since \(\epsilon^2 == 0\), we have
\[ \frac{s}{x + \epsilon \cdot g} = \frac{s \cdot x - \epsilon \cdot sg}{x^2} = \frac{s}{x} - \epsilon \frac{sg}{x^2} \]
Therefore, we should return a jet with \((\frac{s}{\mathrm{value}}, \frac{s}{\mathrm{value}^2}\cdot \mathrm{gradient})\)
Returns
a jet with \((\frac{s}{\mathrm{value}}, \frac{s}{\mathrm{value}^2}\cdot \mathrm{gradient})\)
Definition at line 350 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = s / f.val_;
   res.grad_ = -s * f.grad_ / (f.val_ * f.val_);
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
operator<()
template<typename Dtype , int N> bool cnn::operator< (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
Compare two jets: jet1 < jet2.
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if f.val < g.val; false otherwise
Definition at line 490 of file jet.h.
{
   return f.val_ < g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
operator<<()
template<typename Dtype , int N> std::ostream& cnn::operator<< (std::ostream & os, const Jet< Dtype, N > & f)
Definition at line 186 of file jet.h.
{
   os << f.to_string();
   return os;
 }
References cnn::Jet< Dtype, N >::to_string().
operator<=()
template<typename Dtype , int N> bool cnn::operator<= (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
Compare two jets: jet1 <= jet2.
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if f.val <= g.val; false otherwise
Definition at line 505 of file jet.h.
{
   return f.val_ <= g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
operator==()
template<typename Dtype , int N> bool cnn::operator== (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
compare two jets: jet1 == jet2
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if the values of the two jet are equal; false otherwise
Definition at line 460 of file jet.h.
{
   return f.val_ == g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
operator>()
template<typename Dtype , int N> bool cnn::operator> (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
Compare two jets: jet1 > jet2.
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if f.val > g.val; false otherwise
Definition at line 520 of file jet.h.
{
   return f.val_ > g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
operator>=()
template<typename Dtype , int N> bool cnn::operator>= (const Jet< Dtype, N > & f, const Jet< Dtype, N > & g)
Compare two jets: jet1 >= jet2.
Parameters
f the first jet
g the second jet
Warning
We only consider the value; the gradient of the jet is not considered.
Returns
true if f.val >= g.val; false otherwise
Definition at line 535 of file jet.h.
{
   return f.val_ >= g.val_;
 }
References cnn::Jet< Dtype, N >::val_.
scale_arr() [1/2]
template<typename Dtype > void cnn::scale_arr (Dtype alpha, const Array< Dtype > & src, Array< Dtype > * dst)
dst[i] = alpha * src[i]
Definition at line 119 of file array_math.h.
{
   for (int i = 0; i < src.total_; i++) {
     dst->d_[i] = alpha * src.d_[i];
   }
 }
References cnn::Array< Dtype >::d_, and cnn::Array< Dtype >::total_.
scale_arr() [2/2]
template<typename Dtype > void cnn::scale_arr (int n, Dtype alpha, const Dtype * src, Dtype * dst)
Definition at line 126 of file array_math.h.
{
   for (int i = 0; i < n; i++) {
     dst[i] = alpha * src[i];
   }
 }
set_to() [1/2]
template<typename Dtype > void cnn::set_to (Array< Dtype > * arr, Dtype val)
Set all elements of the array to the specified value.
After this operation, arr[0]=arr[1]=...=arr[total]=val
Parameters
arr the array to be set
val the given value
Definition at line 92 of file array_math.h.
{
   if (!val) {
     memset(arr->d_, 0, sizeof(Dtype) * arr->total_);
   } else  // NOLINT
   {
     for (int i = 0; i < arr->total_; i++) {
       arr->d_[i] = val;
     }
   }
 }
References cnn::Array< Dtype >::d_, and cnn::Array< Dtype >::total_.
set_to() [2/2]
template<typename Dtype > void cnn::set_to (int n, Dtype * arr, Dtype val)
Definition at line 104 of file array_math.h.
{
   if (!val) {
     memset(arr, 0, sizeof(Dtype) * n);
   } else  // NOLINT
   {
     for (int i = 0; i < n; i++) {
       arr[i] = val;
     }
   }
 }
sqrt()
template<typename Dtype , int N> Jet<Dtype, N> cnn::sqrt (const Jet< Dtype, N > & f)
sqrt(jet)
Assume \(f = x + \epsilon \cdot f_x\), then the derivative of \(\sqrt{f}\) with respect to x is \(\frac{1}{2\sqrt{f}} \cdot f_x\).
Thus, we should return a jet \((\sqrt{\mathrm{value}}, \frac{1}{\sqrt{\mathrm{value}}}\)*grad)
Returns
a jet \((\sqrt{\mathrm{value}}, \frac{1}{\sqrt{\mathrm{value}}}\)*grad)
Definition at line 623 of file jet.h.
{
   Jet<Dtype, N> res;
   res.val_ = sqrt(f.val_);
   res.grad_ = f.grad_ / (Dtype(2) * res.val_);
   return res;
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
Referenced by TYPED_TEST().
sub_scalar() [1/2]
template<typename Dtype > void cnn::sub_scalar (Dtype alpha, const Array< Dtype > & src, Array< Dtype > * dst)
dst[i] = src[i] - alpha
Definition at line 166 of file array_math.h.
{
   for (int i = 0; i < src.total_; i++) {
     dst->d_[i] = src.d_[i] - alpha;
   }
 }
References cnn::Array< Dtype >::d_, and cnn::Array< Dtype >::total_.
sub_scalar() [2/2]
template<typename Dtype > void cnn::sub_scalar (int n, Dtype alpha, const Dtype * src, Dtype * dst)
dst[i] = src[i] - alpha
Definition at line 176 of file array_math.h.
{
   for (int i = 0; i < n; i++) {
     dst[i] = src[i] - alpha;
   }
 }
sub_scalar1()
template<typename Dtype > Dtype cnn::sub_scalar1 (const Dtype & x)
Definition at line 42 of file test_jet.cc.
{
   Dtype y;
   y = x - Dtype(1);
   return y;
 }
Referenced by TYPED_TEST().
sub_scalar2()
template<typename Dtype > Dtype cnn::sub_scalar2 (const Dtype & x)
Definition at line 50 of file test_jet.cc.
{
   Dtype y;
   y = Dtype(1) - x;
   return y;
 }
Referenced by TYPED_TEST().
sub_scalar3()
template<typename Dtype > Dtype cnn::sub_scalar3 (const Dtype & x)
Definition at line 58 of file test_jet.cc.
{
   Dtype y(x);
   y -= Dtype(1);
   return y;
 }
Referenced by TYPED_TEST().
sum_arr() [1/2]
template<typename Dtype > Dtype cnn::sum_arr (const Array< Dtype > & src)
res = src[0] + src[1] + src[2] + ...
src[total-1]
Definition at line 136 of file array_math.h.
{
   Dtype res = 0;
   for (int i = 0; i < src.total_; i++) {
     res += src.d_[i];
   }
   return res;
 }
References cnn::Array< Dtype >::d_, and cnn::Array< Dtype >::total_.
sum_arr() [2/2]
template<typename Dtype > Dtype cnn::sum_arr (int n, const Dtype * src)
Definition at line 145 of file array_math.h.
{
   Dtype res = 0;
   for (int i = 0; i < n; i++) {
     res += src[i];
   }
   return res;
 }
sum_squared_arr()
template<typename Dtype > Dtype cnn::sum_squared_arr (int n, const Dtype * src)
Definition at line 154 of file array_math.h.
{
   Dtype res = 0;
   for (int i = 0; i < n; i++) {
     res += src[i] * src[i];
   }
   return res;
 }
TYPED_TEST() [1/27]
cnn::TYPED_TEST (ArrayMathTest , ax_dot_by)
Definition at line 84 of file test_array_math.cc.
{
   Array<TypeParam> arr1;
   Array<TypeParam> arr2;
   arr1.init(1, 1, 2, 3);
   arr2.init(1, 1, 2, 3);
   set_to<TypeParam>(&arr1, 1);
   set_to<TypeParam>(&arr2, 1);
   TypeParam sum = 0;
   sum = ax_dot_by<TypeParam>(arr1.total_, 1, arr1.d_, 1, arr2.d_);
   EXPECT_EQ(sum, arr1.total_);
   sum = 0;
   set_to<TypeParam>(&arr2, 2);
   sum = ax_dot_by<TypeParam>(arr1.total_, -1, arr1.d_, 2, arr2.d_);
   EXPECT_EQ(sum, -arr1.total_ * 4);
 }
References cnn::Array< Dtype >::d_, cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [2/27]
cnn::TYPED_TEST (ArrayMathTest , ax_sub_by_squared)
Definition at line 61 of file test_array_math.cc.
{
   Array<TypeParam> arr1;
   Array<TypeParam> arr2;
   arr1.init(1, 2, 3, 4);
   arr2.init(24, 1, 1, 1);
   set_to<TypeParam>(&arr1, 1);
   set_to<TypeParam>(&arr2, 1);
   double diff = 1000;
   diff = ax_sub_by_squared<TypeParam>(arr1.total_, 1, &arr1(0, 0, 0, 0), 1,
                                       &arr2[0]);
   EXPECT_EQ(diff, 0);
   double sum = 0;
   sum = ax_sub_by_squared<TypeParam>(arr1.total_, -1, &arr1(0, 0, 0, 0), 1,
                                      &arr2[0]);
   EXPECT_EQ(sum, 4 * arr1.total_);
 }
References cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [3/27]
cnn::TYPED_TEST (ArrayMathTest , scale_arr)
Definition at line 104 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = 2;
   d[1] = 3;
   scale_arr<TypeParam>(2, d, &d);
   EXPECT_EQ(d[0], 4);
   EXPECT_EQ(d[1], 6);
   scale_arr<TypeParam>(0.5, d, &d);
   EXPECT_EQ(d[0], 2);
   EXPECT_EQ(d[1], 3);
   scale_arr<TypeParam>(2, 2, &d[0], &d[0]);
   EXPECT_EQ(d[0], 4);
   EXPECT_EQ(d[1], 6);
 }
References cnn::Array< Dtype >::init().
TYPED_TEST() [4/27]
cnn::TYPED_TEST (ArrayMathTest , set_to)
Definition at line 27 of file test_array_math.cc.
{
   int val = 100;
   {
     Array<TypeParam> arr;
     arr.init(2, 3, 4, 5);
     set_to<TypeParam>(&arr, val);
     for (int i = 0; i < arr.total_; i++) {
       EXPECT_EQ(arr[i], val);
     }
     val = 0;
     set_to<TypeParam>(&arr, val);
     for (int i = 0; i < arr.total_; i++) {
       EXPECT_EQ(arr[i], val);
     }
   }
   {
     val = 200;
     Array<TypeParam> arr;
     arr.init(2, 3, 4, 5);
     set_to<TypeParam>(arr.total_, &arr[0], val);
     for (int i = 0; i < arr.total_; i++) {
       EXPECT_EQ(arr[i], val);
     }
     val = 0;
     set_to<TypeParam>(arr.total_, &arr[0], val);
     for (int i = 0; i < arr.total_; i++) {
       EXPECT_EQ(arr[i], val);
     }
   }
 }
References cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [5/27]
cnn::TYPED_TEST (ArrayMathTest , sub_scalar)
Definition at line 149 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = 10;
   d[1] = 5;
   sub_scalar<TypeParam>(2, d, &d);
   EXPECT_EQ(d[0], 8);
   EXPECT_EQ(d[1], 3);
 }
References cnn::Array< Dtype >::init().
TYPED_TEST() [6/27]
cnn::TYPED_TEST (ArrayMathTest , sub_scalar2)
Definition at line 160 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = 10;
   d[1] = 5;
   sub_scalar<TypeParam>(d.total_, 3, &d[0], &d[0]);
   EXPECT_EQ(d[0], 7);
   EXPECT_EQ(d[1], 2);
 }
References cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [7/27]
cnn::TYPED_TEST (ArrayMathTest , sum_arr)
Definition at line 122 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = -1;
   d[1] = 3;
   auto r = sum_arr<TypeParam>(d);
   EXPECT_EQ(r, 2);
 }
References cnn::Array< Dtype >::init().
TYPED_TEST() [8/27]
cnn::TYPED_TEST (ArrayMathTest , sum_arr2)
Definition at line 131 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = -2;
   d[1] = 3;
   auto r = sum_arr<TypeParam>(d.total_, &d[0]);
   EXPECT_EQ(r, 1);
 }
References cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [9/27]
cnn::TYPED_TEST (ArrayMathTest , sum_squared_arr)
Definition at line 140 of file test_array_math.cc.
{
   Array<TypeParam> d;
   d.init(1, 2, 1, 1);
   d[0] = -1;
   d[1] = 3;
   auto r = sum_squared_arr<TypeParam>(2, &d[0]);
   EXPECT_EQ(r, 10);
 }
References cnn::Array< Dtype >::init().
TYPED_TEST() [10/27]
cnn::TYPED_TEST (ArrayTest , at)
Definition at line 90 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(2, 3, 4, 5);
   for (int i = 0; i < arr.total_; i++) arr.d_[i] = i;
   EXPECT_EQ(arr.at(1, 2, 3, 4), 1 * 3 * 4 * 5 + 2 * 4 * 5 + 3 * 5 + 4);
   EXPECT_EQ(arr.at(0, 0, 0, 0), 0);
   EXPECT_EQ(arr.at(0, 0, 0, 4), 4);
   ASSERT_DEATH(arr.at(2, 0, 0, 0), "Check failed: n < n_");
   arr.init(1, 2, 3, 4);
   arr.at(0, 0, 0, 3) = 3;
   EXPECT_EQ(arr.d_[3], 3);
 }
References cnn::Array< Dtype >::at(), cnn::Array< Dtype >::d_, cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [11/27]
cnn::TYPED_TEST (ArrayTest , default_constructor)
Definition at line 38 of file test_array.cc.
{
   Array<TypeParam> arr;
   EXPECT_EQ(arr.d_, nullptr);
   EXPECT_EQ(arr.n_, 0);
   EXPECT_EQ(arr.c_, 0);
   EXPECT_EQ(arr.h_, 0);
   EXPECT_EQ(arr.w_, 0);
   EXPECT_EQ(arr.total_, 0);
 }
References cnn::Array< Dtype >::c_, cnn::Array< Dtype >::d_, cnn::Array< Dtype >::h_, cnn::Array< Dtype >::n_, cnn::Array< Dtype >::total_, and cnn::Array< Dtype >::w_.
TYPED_TEST() [12/27]
cnn::TYPED_TEST (ArrayTest , init)
Definition at line 48 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(1, 1, 1, 2);
   EXPECT_NE(arr.d_, nullptr);
   EXPECT_EQ(arr.n_, 1);
   EXPECT_EQ(arr.c_, 1);
   EXPECT_EQ(arr.h_, 1);
   EXPECT_EQ(arr.w_, 2);
   EXPECT_EQ(arr.total_, 2);
   EXPECT_EQ(isAllZeros(arr), true);
   TypeParam* d = arr.d_;
   arr.init(1, 1, 2, 1);
   EXPECT_EQ(arr.d_, d);  // no memory is re-allocated
   EXPECT_EQ(arr.n_, 1);
   EXPECT_EQ(arr.c_, 1);
   EXPECT_EQ(arr.h_, 2);
   EXPECT_EQ(arr.w_, 1);
   EXPECT_EQ(arr.total_, 2);
   EXPECT_EQ(isAllZeros(arr), true);
   arr.init(2, 3, 4, 5);
   EXPECT_NE(arr.d_, d);  // memory is re-allocated
   EXPECT_EQ(arr.n_, 2);
   EXPECT_EQ(arr.c_, 3);
   EXPECT_EQ(arr.h_, 4);
   EXPECT_EQ(arr.w_, 5);
   EXPECT_EQ(arr.total_, 120);
   EXPECT_EQ(isAllZeros(arr), true);
   d = arr.d_;
   arr.init(3, 2, 5, 4);
   EXPECT_EQ(arr.d_, d);  // no memory is re-allocated
   EXPECT_EQ(arr.n_, 3);
   EXPECT_EQ(arr.c_, 2);
   EXPECT_EQ(arr.h_, 5);
   EXPECT_EQ(arr.w_, 4);
   EXPECT_EQ(arr.total_, 120);
   EXPECT_EQ(isAllZeros(arr), true);
 }
References cnn::Array< Dtype >::c_, cnn::Array< Dtype >::d_, cnn::Array< Dtype >::h_, cnn::Array< Dtype >::init(), isAllZeros(), cnn::Array< Dtype >::n_, cnn::Array< Dtype >::total_, and cnn::Array< Dtype >::w_.
TYPED_TEST() [13/27]
cnn::TYPED_TEST (ArrayTest , move_assignment)
Definition at line 220 of file test_array.cc.
{
   Array<TypeParam> a;
   a.init(2, 3, 4, 5);
   for (int i = 0; i < a.total_; i++) {
     a[i] = i;
   }
   Array<TypeParam> b;
   b = std::move(a);
   EXPECT_EQ(a.n_, 0);
   EXPECT_EQ(a.c_, 0);
   EXPECT_EQ(a.h_, 0);
   EXPECT_EQ(a.w_, 0);
   EXPECT_EQ(a.total_, 0);
   EXPECT_EQ(a.d_, nullptr);
   EXPECT_EQ(b.n_, 2);
   EXPECT_EQ(b.c_, 3);
   EXPECT_EQ(b.h_, 4);
   EXPECT_EQ(b.w_, 5);
   EXPECT_EQ(b.total_, 2 * 3 * 4 * 5);
   for (int i = 0; i < b.total_; i++) {
     EXPECT_EQ(b[i], i);
   }
 }
References cnn::Array< Dtype >::c_, cnn::Array< Dtype >::d_, cnn::Array< Dtype >::h_, cnn::Array< Dtype >::init(), cnn::Array< Dtype >::n_, cnn::Array< Dtype >::total_, and cnn::Array< Dtype >::w_.
TYPED_TEST() [14/27]
cnn::TYPED_TEST (ArrayTest , move_constructor)
Definition at line 194 of file test_array.cc.
{
   Array<TypeParam> a;
   a.init(2, 3, 4, 5);
   for (int i = 0; i < a.total_; i++) {
     a[i] = i;
   }
   Array<TypeParam> b = std::move(a);
   EXPECT_EQ(a.n_, 0);
   EXPECT_EQ(a.c_, 0);
   EXPECT_EQ(a.h_, 0);
   EXPECT_EQ(a.w_, 0);
   EXPECT_EQ(a.total_, 0);
   EXPECT_EQ(a.d_, nullptr);
   EXPECT_EQ(b.n_, 2);
   EXPECT_EQ(b.c_, 3);
   EXPECT_EQ(b.h_, 4);
   EXPECT_EQ(b.w_, 5);
   EXPECT_EQ(b.total_, 2 * 3 * 4 * 5);
   for (int i = 0; i < b.total_; i++) {
     EXPECT_EQ(b[i], i);
   }
 }
References cnn::Array< Dtype >::c_, cnn::Array< Dtype >::d_, cnn::Array< Dtype >::h_, cnn::Array< Dtype >::init(), cnn::Array< Dtype >::n_, cnn::Array< Dtype >::total_, and cnn::Array< Dtype >::w_.
TYPED_TEST() [15/27]
cnn::TYPED_TEST (ArrayTest , operator_bracket)
Definition at line 119 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(2, 3, 4, 5);
   for (int i = 0; i < arr.total_; i++) arr.d_[i] = i;
   EXPECT_EQ(arr[10], 10);
   EXPECT_EQ(arr[100], 100);
   arr.d_[100] = 0;
   EXPECT_EQ(arr[100], 0);
 }
References cnn::Array< Dtype >::d_, cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [16/27]
cnn::TYPED_TEST (ArrayTest , operator_paren)
Definition at line 105 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(2, 3, 4, 5);
   for (int i = 0; i < arr.total_; i++) arr.d_[i] = i;
   EXPECT_EQ(arr(1, 2, 3, 4), 1 * 3 * 4 * 5 + 2 * 4 * 5 + 3 * 5 + 4);
   EXPECT_EQ(arr(0, 0, 0, 0), 0);
   EXPECT_EQ(arr(0, 0, 0, 4), 4);
   arr.init(1, 2, 3, 4);
   arr(0, 0, 0, 3) = 3;
   EXPECT_EQ(arr.d_[3], 3);
 }
References cnn::Array< Dtype >::d_, cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [17/27]
cnn::TYPED_TEST (ArrayTest , operators)
Definition at line 131 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(2, 3, 1, 5);
   int i = 0;
   for (int n = 0; n < 2; n++)
     for (int c = 0; c < 3; c++)
       for (int h = 0; h < 1; h++)
         for (int w = 0; w < 5; w++) {
           arr(n, c, h, w) = i;
           i++;
         }
   for (int k = 0; k < arr.total_; k++) {
     EXPECT_EQ(arr[k], k);
   }
   arr.init(5, 6, 7, 8);
   for (int k = 0; k < arr.total_; k++) {
     arr[k] = k;
   }
   i = 0;
   for (int n = 0; n < 5; n++)
     for (int c = 0; c < 6; c++)
       for (int h = 0; h < 7; h++)
         for (int w = 0; w < 8; w++) {
           EXPECT_EQ(arr(n, c, h, w), i);
           i++;
         }
 }
References cnn::Array< Dtype >::init(), and cnn::Array< Dtype >::total_.
TYPED_TEST() [18/27]
cnn::TYPED_TEST (ArrayTest , proto)
Definition at line 163 of file test_array.cc.
{
   Array<TypeParam> arr;
   arr.init(2, 3, 4, 5);
   for (int i = 0; i < arr.total_; i++) arr.d_[i] = i;
   ArrayProto proto;
   arr.to_proto(&proto);
   EXPECT_EQ(arr.n_, proto.n());
   EXPECT_EQ(arr.c_, proto.c());
   EXPECT_EQ(arr.h_, proto.h());
   EXPECT_EQ(arr.w_, proto.w());
   for (int i = 0; i < arr.total_; i++) {
     EXPECT_EQ(arr[i], proto.d(i));
   }
   Array<TypeParam> arr2;
   arr2.from_proto(proto);
   EXPECT_EQ(arr.n_, arr2.n_);
   EXPECT_EQ(arr.c_, arr2.c_);
   EXPECT_EQ(arr.h_, arr2.h_);
   EXPECT_EQ(arr.w_, arr2.w_);
   EXPECT_EQ(arr.total_, arr2.total_);
   for (int i = 0; i < arr.total_; i++) {
     EXPECT_EQ(arr[i], arr2[i]);
   }
 }
References cnn::Array< Dtype >::c_, cnn::Array< Dtype >::d_, cnn::Array< Dtype >::from_proto(), cnn::Array< Dtype >::h_, cnn::Array< Dtype >::init(), cnn::Array< Dtype >::n_, cnn::Array< Dtype >::to_proto(), cnn::Array< Dtype >::total_, and cnn::Array< Dtype >::w_.
TYPED_TEST() [19/27]
cnn::TYPED_TEST (JetTest , jet_exp_log)
Definition at line 256 of file test_jet.cc.
{
   using Type = Jet<TypeParam, 1>;
   Type x(exp(TypeParam(2)), 0, 10);
   {
     auto f = exp(x);
     auto g = log(f);
     EXPECT_NEAR(g.val_, x.val_, 1e-6);
     EXPECT_NEAR(g.grad_[0], x.grad_[0], 1e-6);
   }
   {
     auto f = log(x);
     auto g = exp(f);
     EXPECT_NEAR(g.val_, x.val_, 1e-6);
     EXPECT_NEAR(g.grad_[0], x.grad_[0], 1e-6);
   }
 }
References exp(), and log().
TYPED_TEST() [20/27]
cnn::TYPED_TEST (JetTest , jet_mul_div_add_test)
Definition at line 222 of file test_jet.cc.
{
   TypeParam x = 1;
   TypeParam y = 2;
   Jet<TypeParam, 2> a(x, 0);
   Jet<TypeParam, 2> b(y, 1);
   auto z = jet_mul_div_add(a, b);
   EXPECT_NEAR(z.val_, jet_mul_div_add(x, y), 1e-6);
   TypeParam dz_dx;
   TypeParam dz_dy;
   dz_dx = (y * y - x * x * y) / ((x * x + y) * (x * x + y));
   dz_dy = x * x * x / ((x * x + y) * (x * x + y));
   EXPECT_NEAR(z.grad_[0], dz_dx, 1e-7);
   EXPECT_NEAR(z.grad_[1], dz_dy, 1e-7);
 }
References jet_mul_div_add().
TYPED_TEST() [21/27]
cnn::TYPED_TEST (JetTest , jet_sqrt)
Definition at line 275 of file test_jet.cc.
{
   using Type = Jet<TypeParam, 1>;
   Type x(exp(TypeParam(2)), 0, 10);
   {
     auto f = sqrt(x);
     auto g = f * f;
     EXPECT_NEAR(g.val_, x.val_, 1e-6);
     EXPECT_NEAR(g.grad_[0], x.grad_[0], 1e-6);
   }
   {
     auto f = x * x;
     auto g = sqrt(f);
     EXPECT_NEAR(g.val_, x.val_, 1e-6);
     EXPECT_NEAR(g.grad_[0], x.grad_[0], 1e-6);
   }
 }
References exp(), and sqrt().
TYPED_TEST() [22/27]
cnn::TYPED_TEST (JetTest , jet_sub_div)
Definition at line 239 of file test_jet.cc.
{
   TypeParam x = 1;
   TypeParam y = 2;
   Jet<TypeParam, 2> a(x, 0);
   Jet<TypeParam, 2> b(y, 1);
   auto z = jet_sub_div(a, b);
   EXPECT_NEAR(z.val_, jet_sub_div(x, y), 1e-7);
   TypeParam dz_dx;
   TypeParam dz_dy;
   dz_dx = 2 * y / ((x + y) * (x + y));
   dz_dy = -2 * x / ((x + y) * (x + y));
   EXPECT_NEAR(z.grad_[0], dz_dx, 1e-7);
   EXPECT_NEAR(z.grad_[1], dz_dy, 1e-7);
 }
References jet_sub_div().
TYPED_TEST() [23/27]
cnn::TYPED_TEST (JetTest , negate)
Definition at line 175 of file test_jet.cc.
{
   Jet<TypeParam, 1> f(10, 0);
   // x = -x
   f = -f;
   EXPECT_EQ(f.val_, -10);
   EXPECT_EQ(f.grad_[0], -1);
 }
References cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
TYPED_TEST() [24/27]
cnn::TYPED_TEST (JetTest , scalar_add)
Definition at line 137 of file test_jet.cc.
{
   Jet<TypeParam, 1> f(10, 0);
   // x = x + 1
   f = add_scalar1(f);
   EXPECT_EQ(f.val_, 11);
   EXPECT_EQ(f.grad_[0], 1);
   // x = 1 + x
   f = add_scalar2(f);
   EXPECT_EQ(f.val_, 12);
   EXPECT_EQ(f.grad_[0], 1);
   // x += 1
   f = add_scalar2(f);
   EXPECT_EQ(f.val_, 13);
   EXPECT_EQ(f.grad_[0], 1);
 }
References add_scalar1(), add_scalar2(), cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
TYPED_TEST() [25/27]
cnn::TYPED_TEST (JetTest , scalar_div)
Definition at line 203 of file test_jet.cc.
{
   Jet<TypeParam, 1> f(10, 0);
   // x = x / 2
   f = div_scalar1(f);
   EXPECT_EQ(f.val_, 5);
   EXPECT_EQ(f.grad_[0], 0.5);
   // x = 2 / x
   f = div_scalar2(f);
   EXPECT_NEAR(f.val_, 0.4, 1e-7);
   EXPECT_EQ(f.grad_[0], -TypeParam(2) / 25 * 0.5);
   // x /= 2
   f = div_scalar3(f);
   EXPECT_NEAR(f.val_, 0.2, 1e-7);
   EXPECT_EQ(f.grad_[0], -TypeParam(2) / 25 * 0.5 * 0.5);
 }
References div_scalar1(), div_scalar2(), div_scalar3(), cnn::Jet< Dtype, N >::grad_, and cnn::Jet< Dtype, N >::val_.
TYPED_TEST() [26/27]
cnn::TYPED_TEST (JetTest , scalar_mul)
Definition at line 184 of file test_jet.cc.
{
   Jet<TypeParam, 1> f(10, 0);
   // x = x * 2
   f = mul_scalar1(f);
   EXPECT_EQ(f.val_, 20);
   EXPECT_EQ(f.grad_[0], 2);
   // x = 2 * x
   f = mul_scalar2(f);
   EXPECT_EQ(f.val_, 40);
   EXPECT_EQ(f.grad_[0], 4);
   // x *= 2
   f = mul_scalar3(f);
   EXPECT_EQ(f.val_, 80);
   EXPECT_EQ(f.grad_[0], 8);
 }
References cnn::Jet< Dtype, N >::grad_, mul_scalar1(), mul_scalar2(), mul_scalar3(), and cnn::Jet< Dtype, N >::val_.
TYPED_TEST() [27/27]
cnn::TYPED_TEST (JetTest , scalar_sub)
Definition at line 156 of file test_jet.cc.
{
   Jet<TypeParam, 1> f(10, 0);
   // x = x - 1
   f = sub_scalar1(f);
   EXPECT_EQ(f.val_, 9);
   EXPECT_EQ(f.grad_[0], 1);
   // x = 1 - x
   f = sub_scalar2(f);
   EXPECT_EQ(f.val_, -8);
   EXPECT_EQ(f.grad_[0], -1);
   // x -= 1
   f = sub_scalar3(f);
   EXPECT_EQ(f.val_, -9);
   EXPECT_EQ(f.grad_[0], -1);
 }
References cnn::Jet< Dtype, N >::grad_, sub_scalar1(), sub_scalar2(), sub_scalar3(), and cnn::Jet< Dtype, N >::val_.
TYPED_TEST_CASE() [1/3]
cnn::TYPED_TEST_CASE (ArrayMathTest , MyTypes)
TYPED_TEST_CASE() [2/3]
cnn::TYPED_TEST_CASE (ArrayTest , MyTypes)
TYPED_TEST_CASE() [3/3]
cnn::TYPED_TEST_CASE (JetTest , MyTypes)